apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: app1
  namespace: flux-system
spec:
  interval: 1m
  # approvePlan: auto
  path: module/examples
  sourceRef:
    kind: GitRepository
    name: app1
    namespace: flux-system
  planOnly: true
  storeReadablePlan: human
  backendConfig:
    disable: true
  cliConfigSecretRef:
    name: az-provider
    namespace: flux-system
